# Generated by Django 3.0.2 on 2020-01-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Turorial',
            new_name='Tutorial',
        ),
    ]
