# Generated by Django 3.0.2 on 2020-02-02 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200130_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 2, 9, 43, 15, 696150), verbose_name='date published'),
        ),
    ]
