# Generated by Django 3.0.2 on 2020-02-07 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200202_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 6, 52, 42, 369330), verbose_name='date published'),
        ),
    ]
