# Generated by Django 3.0.2 on 2020-02-07 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200207_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 9, 9, 15, 987443), verbose_name='date published'),
        ),
    ]
